PSP_EF/PSP_EF/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSP_EF.Models;
using PSP_EF.DAL;
using PSP_EF.BusinessService;
using PSP_EF.Models.ViewModels;

namespace PSP_EF.Controllers
{
    public class PetController : Controller
    {

        private PetLogic _logic;
        private PetDbContext db;
        private PetClassLogic _classLogic;
        //
        // GET: /Pet/

        public ActionResult Index()
        {
         
            
            _logic = new PetLogic();
            var customers = _logic.GetAllCustomers();
            var pets = _logic.GetAllPets(true);
            PetsViewModel model = new PetsViewModel();
           
            model.Pets = pets;
            model.Customers = customers;
            return View("Index",model);

        }

        //
        // GET: /Pet/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    var _classes = db.PetClass;

        //    //ViewBag.PetClassId = new SelectList(db.PetClass, "PetClassId", "Name");

        //    Pet pet = _logic.GetPetById(id);
        //    //Pet pet = db.Pets.Find(id);
        //    if (pet == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(pet);
        //}

        //
        // GET: /Pet/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Username");
            return View();
        }

        //
        // POST: /Pet/Create
        [HttpPost]
        public ActionResult Create(Pet pet)
        {
            if (ModelState.IsValid)
            {
                _logic = new PetLogic();
                _logic.AddPet(pet);
                //db.Pets.Add(pet);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Username", pet.CustomerId);
            return View(pet);
        }              

        //
        // GET: /Pet/Edit/5

        public ActionResult Edit(int id = 0)
        {
            _logic = new PetLogic();
            Pet pet = _logic.GetPetById(id);
            //Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Username", pet.CustomerId);
            return View(pet);
        }

        //
        // POST: /Pet/Edit/5

        [HttpPost]
        public ActionResult Edit(Pet pet)
        {
            if (ModelState.IsValid)
            {
                _logic = new PetLogic();
                _logic.UpdatePet(pet);
                //db.Entry(pet).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Username", pet.CustomerId);
            return View(pet);
        }

        //
        // GET: /Pet/Delete/5

        public ActionResult Delete(int id = 0)
        {
            _logic = new PetLogic();
            Pet pet = _logic.GetPetById(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        //
        // POST: /Pet/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _logic = new PetLogic();
            //Pet pet = _logic.GetPetById(id);
            _logic.DeletePet(id);
            //db.Pets.Remove(pet);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        ///Russelll section crude Update :
        public string UpdateData(string id, string value, string columnPosition)
        {
            if (Request.IsAjaxRequest())
            {
                if (columnPosition == "4" )
                {
                    string str_classId = RetriveIDFromThis(value);
                    _classLogic = new PetClassLogic();
                    if (_classLogic.BookThisClassForMyPet(Convert.ToInt32(str_classId), Convert.ToInt32(id)))
                        return value;
                    else return "Internal problem, plz try later";
                }

                try
                {
                    _logic = new PetLogic();
                    return _logic.UpdatePetAjaxService(Convert.ToInt32(id), value, Convert.ToInt32(columnPosition));
                }
                catch (Exception exp)
                {
                    return exp.Message;
                }
            }
            //SomeOne trying to hack, Implement Somemlogic here :
            return null;
        }

        public ActionResult GetAvailableClassesList()
        {
            
            _classLogic = new PetClassLogic();
            var classes = _classLogic.GetAllClasses(true).ToList();
            Dictionary<string, string> result = new Dictionary<string, string>();
           
            foreach (var cl in classes)
            {
                result.Add(string.Format("{0}-{1}", cl.PetClassId, cl.Name), string.Format("{0}-{1}", cl.PetClassId, cl.Name));
            }
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public int AddData(string customerId, string category, string price,  string description)
        {
            customerId = RetriveIDFromThis(customerId);
            _logic = new PetLogic();
            PetLogic _pLogic = new PetLogic(_logic._petDb);
            try
            {
                Customer owner = _logic.GetCustomerById(Convert.ToInt32(customerId));

               Pet  newpet = new Pet()
                {
                    Customer = owner,
                    CustomerId = owner.CustomerId,
                    PetCategory = category,
                    Description = description,
                    Price =Convert.ToDecimal(price)
                    
                };

               var addedPetId = _pLogic.CreatePet(newpet);
               if (addedPetId > 0)
                {
                    return addedPetId;
                }
                else
                {
                    Response.Write("Some error happened in our dataBase, Refresh the page and try again");
                    Response.StatusCode = 500;
                    Response.End();
                    return -1;
                }
            }
            catch (FormatException)
            {

                Response.Write("Please check your inputs.");
                Response.StatusCode = 404;
                Response.End();
                return -1;
            }
        }

        public string DeleteData(int id)
        {
            try
            {
                PetLogic _petLogic = new PetLogic();

                if (_petLogic.DeletePet(id) ) return "ok";
                else return "The Given Pet Not Found";
            }
            catch (Exception exp)
            {
                return exp.GetType().Equals(typeof(ArgumentNullException)) ? "The Given Pet Not Found" : exp.Message;
            }
        }

        private string RetriveIDFromThis(string src)
        {
           string[] arry = src.Split('-');
           return arry[0];
        }
            
        protected override void Dispose(bool disposing)
        {
            if (db != null) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PSP_EF/PSP_EF/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 60px;
        }
        #searchbar
        {
            padding-bottom: 26px;
            padding-top: 26px;
        }
    </style>
    @RenderSection("style", required: false)
}

<div class="container">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-4">
            <img src="../../Images/psp_logo.gif" alt="logo"/>
        </div>
        <div class="col-lg-6" id="searchbar">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search"/>
                <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Search in <span class="caret"></span></button>
                    <ul class="dropdown-menu pull-right" style="z-index: 1001">
                        <li><a href="#">Pet Adoption</a></li>
                        <li><a href="#">Pet Buying</a></li>
                        <li><a href="#">Pet Service</a></li>
                        <li><a href="#">Pet Class</a></li>
                    </ul>
                </div><!-- /btn-group -->
            </div><!-- /input-group -->
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <nav class="navbar navbar-inverse" role="navigation">
	        <div class="navbar-header">
		        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        </button>
	        </div>
	        <div class="collapse navbar-collapse">
		        <ul class="nav navbar-nav">
			        <li>@Html.ActionLink("Dashboard", "Dashboard", "CustomerAccount")</li>
			        <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pet Service <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Post Service", "PostService", "PetServiceMain")</li>
                            <li>@Html.ActionLink("Search Service", "SearchPetService", "PetServiceMain")</li>
                            <li>@Html.ActionLink("Cancel Service", "CancelService", "PetServiceMain")</li>
				        </ul>
			        </li>
			        <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pet Buying <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Pet Buying", "Buying", "PetBuyingSelling")</li>
                            <li>@Html.ActionLink("Pet Selling", "Selling", "PetBuyingSelling")</li>
				        </ul>
			        </li>
			        <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pet Adoption <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Post Homeless Pet Info", "PostInfo", "Adoption")</li>
					        <li>@Html.ActionLink("Adopt Homeless Pet", "Adoptlist", "Adoption")</li>
				        </ul>
			        </li>
			        <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pet Training <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Pet Class", "Index", "PetClassManager")</li>
                            <li>@Html.ActionLink("Pet Administration Service", "Index", "Pet")</li>
				        </ul>
			        </li>
                    
			        <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lost & Found <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Post Lost", "AddPetLostInfo", "PetLostFound")</li>
					        <li>@Html.ActionLink("Post Lost Pet Info", "PetLostHelpInfo", "PetLostFound")</li>
					        <li>@Html.ActionLink("Post Finding", "PostFinding", "PetLostFound")</li>
					        <li>@Html.ActionLink("Check Lost Report", "TrackReport", "PetLostFound")</li>
                            <li>@Html.ActionLink("Claim Pet", "ClaimPet", "PetLostFound")</li>
				        </ul>
			        </li>

                    <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rating <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Your Transactions", "RateHome", "Rating")</li>
				        </ul>
			        </li>

                    <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Recommendation <b class="caret"></b></a>
				        <ul class="dropdown-menu" role="menu">
					        <li>@Html.ActionLink("Make Recommendation", "Recommending", "Recommendation")</li>
                            <li>@Html.ActionLink("Received Recommendation", "RecommendationList", "Recommendation")</li>
				        </ul>
			        </li>
		        </ul>
	        </div>
        </nav>
    </div>
    @RenderBody()
</div>

@section scripts {
    @RenderSection("scripts", required: false)
}

PSP_EF/PSP_EF/Views/Shared/_LayoutBasic.cshtml
<!DOCTYPE html>
<html lang="en">
	<div id="holder">
    <head>
		<meta charset="utf-8" />
		<title>@ViewBag.Title - My ASP.NET MVC Application</title>
		<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		@Styles.Render("~/Content/bootstrap/base")
		@Styles.Render("~/Content/bootstrap/theme")
		@Scripts.Render("~/bundles/bootstrap")

        <style type ="text/css">
            html,body{
                height: 100%
            }

            #holder{
                min-height: 100%;
                position:relative;
            }

            #body{
                padding-bottom: 100px;    /* height of footer */
            }

            footer{
                height: 100px; 
                width:100%;
                position: absolute;
                left: 0;
                bottom: 0; 
            }
        </style>

		<style type="text/css">
			body 
			{
			    padding-top: 70px;
			}
		</style>
		@RenderSection("style", required: false)
		<script language="javascript" src="/Scripts/datetimepicker.js" type="text/javascript"></script>
		<script language="javascript" src="/Scripts/dateValidation2.js" type="text/javascript"></script>
		<script language="javascript" src="/Scripts/defaultDate2.js" type="text/javascript"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/alphanum.js"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/validEmpty.js"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/isNumeric.js"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/trim.js"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/validateEmail.js"></script>
		<script language="javascript" type="text/javascript" src="/Scripts/inputValidation.js"></script>
	</head>
	<div id="body">
    <body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
                    @Html.ActionLink("PetServicePortal.com", "Index", "Home", null, new { @class = "navbar-brand" })
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a href="@Url.Action("Index", "Home")"><i class="glyphicon glyphicon-home"></i> Home</a></li>
						<li><a href="@Url.Action("About", "Home")"><i class="glyphicon glyphicon-info-sign"></i> About</a></li>
					</ul>
					@Html.Partial("_LoginPartial")
				</div>
			</div>
		</nav>
		@RenderBody()
		<!-- FOOTER -->
		<div class="container">
			<footer>
				<p class="pull-right"><a href="#">Back to top</a></p>
				<p>&copy; 2013 PetServicePortal, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
			</footer>
		</div>
		@Scripts.Render("~/bundles/jquery")
		@Scripts.Render("~/bundles/bootstrap")
		@RenderSection("scripts", required: false)
	</body>
    </div>
    </div>
</html>

PSP_EF/PSP_EF/Views/Shared/_LayoutPostInfo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        .btn-toolbar .btn 
        {
            color: #333333;
            border: 1px solid #cccccc;
            box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
            background-color: #f5f5f5;
        }
    </style>
    @RenderSection("style", required: false)
}

@if (ViewBag.Message != null)
{
    <h6>@ViewBag.Message</h6>
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div class="thumbnail center well well-lg">
                <legend><h1>@RenderSection("form_title", required: true)</h1></legend>
                <form role="form" action="@RenderSection("form_action", required: true)" @RenderSection("form_method", required: true) @RenderSection("form_header_featured", required: false)>
                    @RenderSection("form_field_featured", required: false)
                    <div class="row">
                        <div class="col-lg-3">
                            @RenderSection("form_field_left", required: false)
                        </div>
                        <div class="col-lg-9">
                            <div class="form-group">
                                <label for="editor">Description</label>
                                <div class="hero-unit">
	                                <div class="btn-toolbar" role="toolbar" data-role="editor-toolbar" data-target="#editor">
		                                <div class="btn-group">
			                                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="glyphicon glyphicon-font"></i><b class="caret"></b></a>
			                                <ul class="dropdown-menu"></ul>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="glyphicon glyphicon-text-height"></i>&nbsp;<b class="caret"></b></a>
			                                <ul class="dropdown-menu">
				                                <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
				                                <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
				                                <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
			                                </ul>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="glyphicon glyphicon-bold"></i></a>
			                                <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="glyphicon glyphicon-italic"></i></a>
			                                <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
			                                <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
			                                <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
			                                <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
			                                <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
			                                <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
			                                <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
			                                <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="icon-link"></i></a>
			                                <div class="dropdown-menu input-append">
				                                <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
				                                <button class="btn" type="button">Add</button>
			                                </div>
			                                <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="icon-cut"></i></a>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="icon-picture"></i></a>
			                                <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" class="sr-only"/>
		                                </div>
		                                <div class="btn-group">
			                                <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
			                                <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
		                                </div>
	                                </div>
	                                <div id="editor" class="form-control" style="overflow:scroll; @RenderSection("editor_height_style", required: false); margin-top: 5px"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @RenderSection("form_submit", required: true)
                </form>
            </div>
        </div>
    </div>
}

@RenderBody()

@section scripts {
    <script>
        $(function () {
            function initToolbarBootstrapBindings() {
                var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
                'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
                'Times New Roman', 'Verdana'],
                fontTarget = $('[title=Font]').siblings('.dropdown-menu');
                $.each(fonts, function (idx, fontName) {
                    fontTarget.append($('<li><a data-edit="fontName ' + fontName + '" style="font-family:\'' + fontName + '\'">' + fontName + '</a></li>'));
                });
                $('a[title]').tooltip({ container: 'body' });
                $('.dropdown-menu input').click(function () { return false; })
		        .change(function () { $(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle'); })
            .keydown('esc', function () { this.value = ''; $(this).change(); });

                $('[data-role=magic-overlay]').each(function () {
                    var overlay = $(this), target = $(overlay.data('target'));
                    overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
                });
            };
            function showErrorAlert(reason, detail) {
                var msg = '';
                if (reason === 'unsupported-file-type') { msg = "Unsupported format " + detail; }
                else {
                    console.log("error uploading file", reason, detail);
                }
                $('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>' +
		     '<strong>File upload error</strong> ' + msg + ' </div>').prependTo('#alerts');
            };
            initToolbarBootstrapBindings();
            $('#editor').wysiwyg({ fileUploadError: showErrorAlert });
        });
    </script>
    @RenderSection("scripts", required: false)
}

PSP_EF/PSP_EF/Views/Shared/_LayoutSearching.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        .well-lg
        {
            padding-bottom: 50px;
        }
    </style>
    @RenderSection("style", required: false)
}

<div class="row">
    <div class="col-lg-12">
        <div class="thumbnail center well well-lg">
            @RenderBody()
        </div>
    </div>
</div>

@section scripts {
    @RenderSection("scripts", required: false)
}