PSP_EF/PSP_EF/Controllers/PetServiceMainController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSP_EF.Models;
using PSP_EF.DAL;

namespace PSP_EF.Controllers
{
    public class PetServiceMainController : Controller
    {
        private PetDbContext db = new PetDbContext();

        //
        // GET: /PetServiceMain/

        public ActionResult Index()
        {
            var services = db.Services.Include(s => s.Customer);
            return View(services.ToList());
        }

        //
        // GET: /PetServiceMain/Details/5

        public ActionResult Details(int id = 0)
        {
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        //
        // GET: /PetServiceMain/Create

        public ActionResult Create()
        {
            ViewBag.ProviderId = new SelectList(db.Customers, "CustomerId", "Username");
            return View();
        }

        //
        // POST: /PetServiceMain/Create

        [HttpPost]
        public ActionResult Create(Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProviderId = new SelectList(db.Customers, "CustomerId", "Username", service.ProviderId);
            return View(service);
        }

        //
        // GET: /PetServiceMain/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProviderId = new SelectList(db.Customers, "CustomerId", "Username", service.ProviderId);
            return View(service);
        }

        //
        // POST: /PetServiceMain/Edit/5

        [HttpPost]
        public ActionResult Edit(Service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProviderId = new SelectList(db.Customers, "CustomerId", "Username", service.ProviderId);
            return View(service);
        }

        //
        // GET: /PetServiceMain/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        //
        // POST: /PetServiceMain/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PostService()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult PostService(Service cService)
        {
            //@ViewBag.Message = cPet.Description;
            //var cityId = Request.Form["citylist"];
            Customer currentUser = (Customer)Session["currentUser"];
            int customerId = currentUser.CustomerId;

            cService.ProviderId = customerId;

            db.Services.Add(cService);
            db.SaveChanges();

            ViewBag.Message = "Your service has been posted. Thank you for using our service.";

            return View();
        }

        public ActionResult SearchPetService()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchPetServiceResult(Service cService, decimal fromPrice = -12, decimal toPrice = -12)
        {
            // get list of all valid services
            var theService = (from customer in db.Customers
                              join service in db.Services on customer.CustomerId equals service.ProviderId
                              where service.ServiceName.Equals(cService.ServiceName)
                              where !(from trans in db.Transactions select trans.ServiceId).Contains(service.ServiceId)
                              select new SearchServiceResult
                              {
                                  service_id = service.ServiceId,
                                  service_provider_id = service.ProviderId,
                                  service_provider_name = customer.FirstName + " " + customer.LastName,
                                  service_type = service.ServiceName,
                                  service_desc = service.Description,
                                  service_price = (decimal)service.Price
                              }).Distinct();

            // Check whether user input a minimum value or maximum value for price
            // if the user only input the minimum price, then only minimum price is set
            // if the user only input the maximum price, then only the maximum price is set
            // if the user input both minimum & maximum price, then the price range is set
            if (!(fromPrice == -12))
            {
                theService = theService.Where(x => x.service_price >= fromPrice);
            }

            if (!(toPrice == -12))
            {
                theService = theService.Where(x => x.service_price <= toPrice);
            }
            //List<SearchPetResult> test = petForSale.ToList();
            //ViewData["petForSale"] = petForSale.ToList();
            //SearchPetResult petForSaleModel = (SearchPetResult)petForSale;
            return View(theService.AsEnumerable());
        }

        public ActionResult HireProcess(int serviceId = 0)
        {
            //Service theService = db.Services.Find(serviceId);
            var cUser = (Customer)Session["currentUser"];
            Transaction trans = new Transaction();

            trans.CustomerId = cUser.CustomerId; 
            trans.ServiceId = serviceId; 
            trans.Date = System.DateTime.Now;
            trans.Status = "Finished";

            //Pet pet = db.Pet.Find(id);

            if (ModelState.IsValid)
            {
                db.Transactions.Add(trans);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult CancelService()
        {
            var cUser = (Customer)Session["currentUser"];
            int customerId = cUser.CustomerId;

            var theService = (from service in db.Services
                              join trans in db.Transactions on service.ServiceId equals trans.ServiceId
                              join customer in db.Customers on service.ProviderId equals customer.CustomerId
                              where trans.CustomerId.Equals(customerId)
                              && ( service.ServiceName.Contains("Walking") 
                              || service.ServiceName.Contains("Sitting")  
                              || service.ServiceName.Contains("Saloon")
                              || service.ServiceName.Contains("Washing"))
                              select new SearchServiceResult
                              {
                                  service_id = service.ServiceId,
                                  service_provider_id = service.ProviderId,
                                  service_provider_name = customer.FirstName + " " + customer.LastName,
                                  service_type = service.ServiceName,
                                  service_desc = service.Description,
                                  service_price = (decimal)service.Price
                              }).Distinct();

            /*var theService = (from trans in db.Transactions
                              join service in db.Services on trans.ServiceId equals service.ServiceId
                              join customer in db.Customers on customer.customerId equals service.providerId 
                              where trans.CustomerId.Equals(customerId)
                              where service.ServiceName.Contains("Walking")
                              where service.ServiceName.Contains("Sitting")
                              where service.ServiceName.Contains("Saloon")
                              where service.ServiceName.Contains("Washing")
                              select new SearchServiceResult
                              {
                                  service_id = service.ServiceId,
                                  service_provider_id = service.ProviderId,
                                  service_provider_name = customer.FirstName + " " + customer.LastName,
                                  service_type = service.ServiceName,
                                  service_desc = service.Description,
                                  service_price = (decimal)service.Price
                              }).Distinct();*/

            return View(theService.AsEnumerable());
        }

        public ActionResult CancelServiceProcess(int serviceId = 0)
        {
            var remove = (from trans in db.Transactions
                          where trans.ServiceId == serviceId
                          select trans).FirstOrDefault();

            if (remove != null)
            {
                db.Transactions.Remove(remove);
                db.SaveChanges();
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PSP_EF/PSP_EF/Views/PetServiceMain/CancelService.cshtml
@model IEnumerable<PSP_EF.Models.SearchServiceResult>
@{
    ViewBag.Title = "Cancel Service";
}

<h2>Cancel Service</h2>

@foreach (var item in Model)
{
    <p>Service Provider ID :
    @Html.DisplayFor(modelItem => item.service_provider_id)</p>
    
    <p>Service Provider Name : 
    @Html.DisplayFor(modelItem => item.service_provider_name)    </p>
    
    <p>Service Type : 
    @Html.DisplayFor(modelItem => item.service_type)    </p>
    
    <p>Service Description : 
    @Html.DisplayFor(modelItem => item.service_desc)    </p>
    
    <p>Service Price : 
    @Html.DisplayFor(modelItem => item.service_price)    </p>
    
    @Html.ActionLink("Cancel Hiring", "CancelServiceProcess", new { serviceId = item.service_id })
    <br /><br />
}

PSP_EF/PSP_EF/Views/PetServiceMain/CancelServiceProcess.cshtml
@{
    ViewBag.Title = "CancelServiceProcess";
}

<h6>Cancel Service</h6>
<h6>This service has been cancelled. Your service provider will be very sad.</h6>

PSP_EF/PSP_EF/Views/PetServiceMain/Create.cshtml
@model PSP_EF.Models.Service

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Service</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProviderId, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProviderId", String.Empty)
            @Html.ValidationMessageFor(model => model.ProviderId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PetId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetId)
            @Html.ValidationMessageFor(model => model.PetId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ServiceName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ServiceName)
            @Html.ValidationMessageFor(model => model.ServiceName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PSP_EF/PSP_EF/Views/PetServiceMain/Delete.cshtml
@model PSP_EF.Models.Service

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Service</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.Username)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.Username)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PetId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ServiceName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServiceName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PSP_EF/PSP_EF/Views/PetServiceMain/Details.cshtml
@model PSP_EF.Models.Service

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Service</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.Username)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.Username)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PetId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ServiceName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServiceName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ServiceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PSP_EF/PSP_EF/Views/PetServiceMain/Edit.cshtml
@model PSP_EF.Models.Service

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Service</legend>

        @Html.HiddenFor(model => model.ServiceId)

        <div class="editor-label">
            @Html.LabelFor(model => model.ProviderId, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProviderId", String.Empty)
            @Html.ValidationMessageFor(model => model.ProviderId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PetId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetId)
            @Html.ValidationMessageFor(model => model.PetId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ServiceName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ServiceName)
            @Html.ValidationMessageFor(model => model.ServiceName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PSP_EF/PSP_EF/Views/PetServiceMain/HireProcess.cshtml
@{
    ViewBag.Title = "Hire Process";
}

<h2>Thank you for selecting our pet provider. Please proceed with the payment. </h2>

PSP_EF/PSP_EF/Views/PetServiceMain/Index.cshtml
@model IEnumerable<PSP_EF.Models.Service>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ServiceId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ServiceId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ServiceId })
        </td>
    </tr>
}

</table>

PSP_EF/PSP_EF/Views/PetServiceMain/PostService.cshtml
@{
    ViewBag.Title = "Post Service";
    Layout = "~/Views/Shared/_LayoutSearching.cshtml";
}

@model PSP_EF.Models.Service
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            margin-top: 30px;
            margin-bottom: 30px;
        }
    </style>
}

<h2>Post Service</h2>

@if (ViewBag.Message != null)
{
    <h6>@ViewBag.Message</h6>
}
else
{
<form role="form" class="col-lg-9 form-horizontal" action="@Url.Action("PostService", "PetServiceMain")" method="post" onsubmit="return validateNumber()">
    @Html.HiddenFor(model => model.ServiceId)
    <div class="form-group">
        <label for="PetCategory" class="col-sm-3 control-label">Service Category</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.ServiceName, new SelectList(new List<Object>{
                    new {value = "Pet Walking", text = "Pet Walking"},
                    new {value = "Pet Sitting", text = "Pet Sitting"},
                    new {value = "Pet Saloon", text = "Pet Saloon"},
                    new {value = "Pet Washing", text = "Pet Washing"}
                }, "value", "text", "Pet Walking"))
            </div>
    </div>
    <div class="form-group">
        <label for="@Html.DisplayNameFor(model => model.Description)" class="col-sm-3 control-label">Description</label>
        <div class="col-sm-9">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "Please enter the service description" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Html.DisplayNameFor(model => model.Price)" class="col-sm-3 control-label">Price</label>
        <div class="col-sm-9">
                @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @placeholder = "Please enter the price" })
        </div>
    </div>
    <button type="submit" class="btn btn-default btn-primary">Post Service Info</button>
</form>
}

@section scripts {
    <script type="text/javascript">
        $('#DOBPicker').datetimepicker({
            weekStart: 1,
            autoclose: 1,
            startView: 2,
            minView: 2,
            endDate: new Date(),
            forceParse: 1
        });
    </script>

}

PSP_EF/PSP_EF/Views/PetServiceMain/SearchPetService.cshtml
@model PSP_EF.Models.Service

@{
    ViewBag.Title = "SearchPetService";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            margin-top: 30px;
            margin-bottom: 30px;
        }
    </style>
}

<h2>Hire Service</h2>

<form role="form" class="col-lg-9 form-horizontal" action="@Url.Action("SearchPetServiceResult", "PetServiceMain")" method="post" onsubmit="return validateNumberRange()">
    <div class="form-group">
        <label for="PetCategory" class="col-sm-3 control-label">Service Type:</label>
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.ServiceName, new SelectList(new List<Object>{
                    new {value = "Pet Walking", text = "Pet Walking"},
                    new {value = "Pet Sitting", text = "Pet Sitting"},
                    new {value = "Pet Saloon", text = "Pet Saloon"},
                    new {value = "Pet Washing", text = "Pet Washing"}
                }, "value", "text", "Pet Walking"))
            </div>
    </div>

    <div class="form-group">
        <label for="@Html.DisplayNameFor(model => model.Price)" class="col-sm-3 control-label">Price Range</label>
        <div class="col-sm-9">
                @Html.TextBox("fromPrice")
                to
                @Html.TextBox("toPrice")
        </div>
    </div>

    <button type="submit" class="btn btn-default btn-primary">Search</button>
</form>


@section scripts {
    <script type="text/javascript">
        $('#DOBPicker').datetimepicker({
            weekStart: 1,
            autoclose: 1,
            startView: 2,
            minView: 2,
            endDate: new Date(),
            forceParse: 1
        });
    </script>

}

PSP_EF/PSP_EF/Views/PetServiceMain/SearchPetServiceResult.cshtml
@{
    ViewBag.Title = "Search Pet Service";
}

@model IEnumerable<PSP_EF.Models.SearchServiceResult>


<h2>Search Result</h2>

@foreach (var item in Model)
{
    <p>Service Provider ID :
    @Html.DisplayFor(modelItem => item.service_provider_id)</p>
    
    <p>Service Provider Name : 
    @Html.DisplayFor(modelItem => item.service_provider_name)    </p>
    
    <p>Service Type : 
    @Html.DisplayFor(modelItem => item.service_type)    </p>
    
    <p>Service Description : 
    @Html.DisplayFor(modelItem => item.service_desc)    </p>
    
    <p>Service Price : 
    @Html.DisplayFor(modelItem => item.service_price)    </p>
    
    @Html.ActionLink(" Hire this service provider", "HireProcess", new { serviceId = item.service_id })
    <br /><br />
}