PSP_EF/PSP_EF/Controllers/PetBuyingSellingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSP_EF.DAL;
using PSP_EF.Models;

namespace PSP_EF.Controllers
{
    public class PetBuyingSellingController : Controller
    {
        public PetDbContext db = new PetDbContext();

        //
        // GET: /PetBuyingSelling/

        public ActionResult Index()
        {
            var pets = db.Pets.Include(p => p.Customer);
            return View(pets.ToList());
        }

        //
        // GET: /PetBuyingSelling/Details/5

        public ActionResult Details(int id = 0)
        {
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        //
        // GET: /PetBuyingSelling/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName");
            return View();
        }

        //
        // POST: /PetBuyingSelling/Create

        [HttpPost]
        public ActionResult Create(Pet pet)
        {
            if (ModelState.IsValid)
            {
                db.Pets.Add(pet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", pet.CustomerId);
            return View(pet);
        }

        //
        // GET: /PetBuyingSelling/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", pet.CustomerId);
            return View(pet);
        }

        //
        // POST: /PetBuyingSelling/Edit/5

        [HttpPost]
        public ActionResult Edit(Pet pet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", pet.CustomerId);
            return View(pet);
        }

        //
        // GET: /PetBuyingSelling/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        //
        // POST: /PetBuyingSelling/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pet pet = db.Pets.Find(id);
            db.Pets.Remove(pet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //POST: /PetBuyingSelling/Search/
        /*[HttpPost]
        public ActionResult Search(String searchText, decimal fromPrice = -1234, decimal toPrice = -1234)
        {

            //if (fromPrice == null)
            //  fromPrice = 54;
            ViewBag.Message = fromPrice;
            //return RedirectToAction("Search") ;

            var petList = from p in db.Pets //where (p.Pet_Category == searchText)
                          select p;


            //decimal? convertedFromAmount = fromPrice;
            //decimal? convertedToAmount = toPrice;

            if (!String.IsNullOrEmpty(searchText))
            {
                petList = petList.Where(s => s.PetCategory.Contains(searchText));
            }

            if (!(fromPrice == -1234))
            {
                petList = petList.Where(x => x.Price >= fromPrice);// && p.Price == convertedFromAmount
            }

            if (!(toPrice == -1234))
            {
                petList = petList.Where(x => x.Price <= toPrice);// && p.Price == convertedFromAmount
            }

            /*if (!String.IsNullOrEmpty(searchText))
            {
                petList = petList.Where(s => s.Pet_Category.Contains(searchText));
            }

            if (fromPrice.)
            {
                petList = petList.Where(x => x.Price == fromPrice);
            }*/
            //return View(petList.ToList());
        //}
        /*
        public ActionResult Buy(int id = 0)
        {
            Transaction trans = new Transaction();

            var cUser = (Customer)Session["currentUser"];
            int customerId = cUser.CustomerId;

            trans.CustomerId = customerId; // hard coded
            trans.ServiceId = 1; // hard coded
            trans.Date = System.DateTime.Now;
            trans.Status = "Customer submit the offer";

            //Pet pet = db.Pet.Find(id);

            if (ModelState.IsValid)
            {
                db.Transactions.Add(trans);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            /*
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);*/
            //return View();
        //}

        // GET:/PetBuyingSelling/Buying/
        // get the initial page for buying a pet
        public ActionResult Buying()
        {
            return View();
        }

        // POST:/PetBuyingSelling/SearchResult/
        // Show the search result and option to buy
        public ActionResult SearchResult(Pet cPet, decimal fromPrice = -12, decimal toPrice = -12)
        {
            // get list of all pets which is going to be sold by their owners.
            var petForSale = (from thePets in db.Pets
                              join theOwner in db.Customers on thePets.CustomerId equals theOwner.CustomerId
                              join service in db.Services on thePets.PetId equals service.PetId
                              where service.ServiceName.StartsWith("Pet Selling by ")
                              where thePets.PetCategory.Equals(cPet.PetCategory)
                              where !thePets.TransactionId.HasValue
                              select new SearchPetResult
                              {
                                  service_id = service.ServiceId,
                                  pet_owner_name = theOwner.FirstName + " " + theOwner.LastName,
                                  pet_category = thePets.PetCategory,
                                  pet_desc = thePets.Description,
                                  pet_price = (decimal)thePets.Price
                              }).Distinct();


            // Check whether user input a minimum value or maximum value for price
            // if the user only input the minimum price, then only minimum price is set
            // if the user only input the maximum price, then only the maximum price is set
            // if the user input both minimum & maximum price, then the price range is set
            if (!(fromPrice == -12))
            {
                petForSale = petForSale.Where(x => x.pet_price >= fromPrice);
            }

            if (!(toPrice == -12))
            {
                petForSale = petForSale.Where(x => x.pet_price <= toPrice);
            }
            //List<SearchPetResult> test = petForSale.ToList();
            //ViewData["petForSale"] = petForSale.ToList();
            //SearchPetResult petForSaleModel = (SearchPetResult)petForSale;
            return View(petForSale.AsEnumerable());
        }

        // GET: /PetBuyingSelling/Selling/
        // get the initial page for selling a pet
        public ActionResult Selling()
        {
            return View();
        }

        // POST: /PetBuyingSelling/Selling/
        // get the initial page for selling
        [HttpPost, ValidateInput(false)]
        public ActionResult Selling(Pet cPet)
        {
            //@ViewBag.Message = cPet.Description;
            //var cityId = Request.Form["citylist"];
            Customer currentUser = (Customer)Session["currentUser"];
            int customerId = currentUser.CustomerId;

            cPet.CustomerId = customerId;
            if (cPet.Description == null)
            {
                cPet.Description = "";
            }
            db.Pets.Add(cPet);
            db.SaveChanges();

            Service newService = new Service();
            newService.ProviderId = customerId;
            newService.PetId = cPet.PetId;
            newService.ServiceName = "Pet Selling by " + currentUser.FirstName + " " + currentUser.LastName;
            newService.Description = "Ordinary pet selling transaction";
            newService.Price = cPet.Price;
            db.Services.Add(newService);
            db.SaveChanges();

            ViewBag.Message = "Your pet info has been posted. Thank you for using our service.";

            return View();
        }

        public ActionResult BuyProcess(int serviceId = 0)
        {
            int petId = 0;
            var cUser = (Customer)Session["currentUser"];
            Transaction trans = new Transaction();

            trans.CustomerId = cUser.CustomerId;
            trans.ServiceId = serviceId;
            trans.Date = System.DateTime.Now;
            trans.Status = "Finished";

            if (ModelState.IsValid)
            {
                db.Transactions.Add(trans);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            /* Service theService = db.Services.Find(serviceId);
             db.Services.Remove(theService);
             db.SaveChanges();*/

            var getPetId = (from service in db.Services
                            where service.ServiceId.Equals(serviceId)
                            select new { service.PetId });

            foreach (var c in getPetId)
            {

PSP_EF/PSP_EF/Views/PetBuyingSelling/Buy.cshtml
@{
    ViewBag.Title = "Buy";
}

<h2>You have successfully buy this pet</h2>

PSP_EF/PSP_EF/Views/PetBuyingSelling/BuyProcess.cshtml
@{
    ViewBag.Title = "Buy a Pet";
}

<h2>Thank you for your purchase. Please proceed with the payment. </h2>

PSP_EF/PSP_EF/Views/PetBuyingSelling/Buying.cshtml
@{
    ViewBag.Title = "Buy Pets";
    Layout = "~/Views/Shared/_LayoutSearching.cshtml";
}


@model PSP_EF.Models.Pet

@{
    var prod = ViewData["petForSale"];
}

<legend><h1>Buy a Pet</h1></legend>
<p>Search a pet to buy.</p>
<form role="form" action="@Url.Action("SearchResult", "PetBuyingSelling")" method="post" onsubmit="return validateNumberRange()">
    <div class="row">
        <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2 input-group">
                <div class="input-group-btn">
                    @Html.DropDownListFor(model => model.PetCategory, new SelectList(new List<Object>{
                        new {value = "Cat", text = "Cat"},
                        new {value = "Dog", text = "Dog"},
                        new {value = "Rabbit", text = "Rabbit"},
                        new {value = "Other", text = "Other"}
                    }, "value", "text", "Cat"), new { @class = "form-control required", @style = " width:150px" })
                </div>
                @Html.TextBox("fromPrice", null, new { @class = "form-control required", @placeholder="Price from ..."})
                <span class="input-group-addon">to</span>
                @Html.TextBox("toPrice", null, new { @class = "form-control", @placeholder = "..." })
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i>&nbsp;Search</button>
                </div>     
            </div>
        </div>
    </div>
</form>

PSP_EF/PSP_EF/Views/PetBuyingSelling/Create.cshtml
@model PSP_EF.Models.Pet

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pet</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerId, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerId", String.Empty)
            @Html.ValidationMessageFor(model => model.CustomerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TransactionId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TransactionId)
            @Html.ValidationMessageFor(model => model.TransactionId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PetCategory)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetCategory)
            @Html.ValidationMessageFor(model => model.PetCategory)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PSP_EF/PSP_EF/Views/PetBuyingSelling/Delete.cshtml
@model PSP_EF.Models.Pet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Pet</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TransactionId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TransactionId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PetCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetCategory)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PSP_EF/PSP_EF/Views/PetBuyingSelling/Details.cshtml
@model PSP_EF.Models.Pet

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Pet</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TransactionId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TransactionId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PetCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetCategory)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.PetId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PSP_EF/PSP_EF/Views/PetBuyingSelling/Edit.cshtml
@model PSP_EF.Models.Pet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pet</legend>

        @Html.HiddenFor(model => model.PetId)

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerId, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerId", String.Empty)
            @Html.ValidationMessageFor(model => model.CustomerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TransactionId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TransactionId)
            @Html.ValidationMessageFor(model => model.TransactionId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PetCategory)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetCategory)
            @Html.ValidationMessageFor(model => model.PetCategory)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PSP_EF/PSP_EF/Views/PetBuyingSelling/Index.cshtml
@model IEnumerable<PSP_EF.Models.Pet>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<form action="@Url.Action("Search", "PetBuying")" method="post">
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetCategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PetId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PetId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PetId })
        </td>
    </tr>
}
 <tr>
        <td>
            Search:
        </td>
        <td>

            @Html.TextBox("searchText")    
            
        </td>
        <td>
            <button type="submit">Search</button>
        </td>     
    </tr>
    <tr>
        <td>
            Min:  
        </td> 
        <td>
            @Html.TextBox("fromPrice")   
        </td>
        <td>
            Max: 
        </td>
        <td>
            @Html.TextBox("toPrice")
        </td>
    </tr>
</table>
</form>

PSP_EF/PSP_EF/Views/PetBuyingSelling/Search.cshtml
@model IEnumerable<PSP_EF.Models.Pet> 

@{
    ViewBag.Title = "Search";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>
<h1>@ViewBag.Message</h1>

<table>
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PetId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Buy this pet", "Buy", new { id = item.PetId })
        </td>
    </tr>
}
</table>

PSP_EF/PSP_EF/Views/PetBuyingSelling/SearchResult.cshtml
@model IEnumerable<PSP_EF.Models.SearchPetResult>

@{
    ViewBag.Title = "Search Result";
    const int ROWS_PER_PAGE = 10;
    int currentFirst = 1;
    int currentLast = ROWS_PER_PAGE;
    int total = 0;
    foreach (var item in Model) {total++;}
    bool showPageBar = false;
    int readCurrentPage = 1; // TODO: read current page
    if (total < currentLast) {
        currentLast = total;
        showPageBar = false;
    } else {
        currentFirst = (readCurrentPage - 1) * ROWS_PER_PAGE + 1;
        currentLast = readCurrentPage * ROWS_PER_PAGE;
        showPageBar = true;
    }
    int index = 1;
}

<div class="row">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Buying", "PetBuyingSelling")">Buying Pets</a></li>
        <li class="active">@currentFirst - @currentLast of @total</li>
    </ol>
</div>

@if (showPageBar)
{
    <div class="row">
        <ul class="pagination pagination-large">
            <li><a href="#1">&laquo;</a></li>
            @for (int i = 1; i <= (total + ROWS_PER_PAGE - 1) / ROWS_PER_PAGE; i++)
            {
                if (i == readCurrentPage)
                {
                    <li class="active"><span>@i</span></li>
                }
                else
                {
                    <li><a href="#@i">@i</a></li>
                }

            }
            <li><a href="#@((total + ROWS_PER_PAGE - 1) / ROWS_PER_PAGE)">&raquo;</a></li>
        </ul>
    </div>
}


@foreach (var item in Model)
{
    <div class="row">
        <div class="panel panel-default col-sm-10 col-sm-offset-1">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-3">
                        <img src="../../Images/pet_no_photo.png" class="img-thumbnail img-responsive" style="max-height:140px"/>
                    </div>
                    <div class="col-sm-6">
                        <h3>@Html.DisplayFor(modelItem => item.pet_category)</h3>
                        @Html.DisplayTextFor(modelItem => item.pet_desc)
                    </div>
                    <div class="col-sm-3">
                        <p><i class="glyphicon glyphicon-user"></i>&nbsp @Html.DisplayFor(modelItem => item.pet_owner_name)</p>
                        <h4>AU$ @Html.DisplayFor(modelItem => item.pet_price)</h4>
                        @Html.ActionLink("Buy this pet", "BuyProcess", new { serviceId = item.service_id }, new { @class = "btn btn-primary btn-lg", @role = "button" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@if (showPageBar)
{
    <div class="row">
        <ul class="pagination pagination-large">
            <li><a href="#1">&laquo;</a></li>
            @for (int i = 1; i <= (total + ROWS_PER_PAGE - 1) / ROWS_PER_PAGE; i++)
            {
                if (i == readCurrentPage)
                {
                    <li class="active"><span>@i</span></li>
                }
                else
                {
                    <li><a href="#@i">@i</a></li>
                }

            }
            <li><a href="#@((total + ROWS_PER_PAGE - 1) / ROWS_PER_PAGE)">&raquo;</a></li>
        </ul>
    </div>
}

PSP_EF/PSP_EF/Views/PetBuyingSelling/Selling.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPostInfo.cshtml";
}

@model PSP_EF.Models.Pet

@{
    ViewBag.Title = "Selling";
}

@if (ViewBag.Message == null)
{
    @section form_title {Sell a Pet }

    @section form_action {@Url.Action("Selling", "PetBuyingSelling")}

    @section form_method {method="post"}

    @section form_header_featured {onsubmit="return (transferEditorToDescription() && validateNumber())"}

    @section form_field_featured {
        @Html.HiddenFor(model => model.PetId)
        @Html.HiddenFor(model => model.Description)
    }

    @section form_field_left {
        <p>Describe the pet you want to sell.</p>
        <div class="form-group">
            <p><img src="../../Images/pet_no_photo.png" class="img-thumbnail img-responsive" height="80"/></p>
            <label for="PetPicture">Pet Picture</label>
            <input type="file" id="PetPicture">
        </div>
        <div class="form-group">
            <label for="@Html.DisplayNameFor(model => model.PetCategory)">Pet Category*</label>
            @Html.DropDownListFor(model => model.PetCategory, new SelectList(new List<Object>{
                new {value = "Cat", text = "Cat"},
                new {value = "Dog", text = "Dog"},
                new {value = "Rabbit", text = "Rabbit"},
                new {value = "Other", text = "Other"}
            }, "value", "text", "Cat"), new { @class = "form-control required" })
        </div>
        <div class="form-group">
            <label for="@Html.DisplayNameFor(model => model.Price)">Price*</label>
            <div class="input-group">
                <span class="input-group-addon">AUD</span>
                @Html.TextBoxFor(model => model.Price, new { @class = "form-control required", @placeholder = "Please enter the price" })
            </div>
        </div>
    }

    @section form_submit {
        <button type="submit" class="btn btn-default btn-primary">Post Sell Info</button>
    }

    @section editor_height_style { height: 420px; }
}