PSP_EF/PSP_EF/Controllers/CustomerAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSP_EF.DAL;
using PSP_EF.Models;
using System.Data.Entity.Validation;

namespace PSP_EF.Controllers
{
    public class CustomerAccountController : Controller
    {
        private PetDbContext db = new PetDbContext();

        //
        // GET: /CustomerAccount/

        public ActionResult Index()
        {
            var customers = db.Customers.Include(c=>c.City);
            return View(customers.ToList());
        }

        //
        // GET: /CustomerAccount/Details/5

        public ActionResult Details(int id = 0)
        {
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // GET: /CustomerAccount/Create

        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name");
            return View();
        }

        //
        // POST: /CustomerAccount/Create

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", customer.CityId);
            return View(customer);
        }

        //
        // GET: /CustomerAccount/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", customer.CityId);
            return View(customer);
        }

        //
        // POST: /CustomerAccount/Edit/5

        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", customer.CityId);
            return View(customer);
        }

        //
        // GET: /CustomerAccount/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /CustomerAccount/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET route for: /CustomerAccount/Register
        public ActionResult Register()
        {
            ViewBag.citylist = getCities();

            return View("Register");
        }

        // POST route for: /CustomerAccount/Register
        [HttpPost]
        public ActionResult Register(Customer cModel)
        {
            var cityId = Request.Form["citylist"];
            ViewBag.citylist = getCities();

            ViewBag.Message = "Thank you for registering. ";

            //check whether the email is already exist or not
            var customer = from p in db.Customers
                           select p;
            customer = customer.Where(s => s.Email.Equals(cModel.Email));
            if (customer.Count() != 0)
            {
                ViewBag.Message = null;
                ViewBag.ErrorMessage = "Your email address is already exists. Please choose another email address.";
                return View();
            }
            else
            {
                cModel.JoinedDate = DateTime.Now;
                cModel.LastUpdate = DateTime.Now;
                cModel.CityId = Convert.ToInt16(cityId);
                db.Customers.Add(cModel);
                db.SaveChanges();
                Session["currentUser"] = cModel;
                return View("Dashboard");
            }
        }

        //
        // GET route for: /CustomerAccount/Login
        // Redirect user to login page for the first time
        public ActionResult Login()
        {
            return View("Login");
        }

        
        // POST route for: /CustomerAccount/Login
        // Redirect user to appropriate page after login
        [HttpPost]
        public ActionResult Login(Customer cModel)
        {
            //check whether the customer is in the database and using the correct email & password
            var customer = from p in db.Customers
                          select p;

            customer = customer.Where(s => s.Email.Equals(cModel.Email));
            customer = customer.Where(s => s.Password.Equals(cModel.Password));

            //validating the customer email and password
            if (customer.Count() == 0 || cModel.Email == "" || cModel.Password == "")
            {
                ViewBag.Message = "Wrong email or password";
                return View("Login");
            }
            else
            {
                //foreach (var c in customer)
                //{
                Session["currentUser"] = customer.First();
                //}
                return View("Dashboard");
            }
        }

        // GET route for: /CustomerAccount/EditDetails
        public ActionResult EditDetails()
        {
            var cModel = (Customer)Session["currentUser"];

            Customer customer = db.Customers.Find(cModel.CustomerId);

            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", customer.CityId);
            //ViewBag.citylist = getCities();
            if (cModel.DateOfBirth != null)
            {
                DateTime date1 = (DateTime)cModel.DateOfBirth;
                ViewBag.dateValue = date1.ToString("MM/dd/yyyy");
            }
            //cModel.DateOfBirth = cModel.DateOfBirth.ToString("MM/dd/YYYY");
            //var model = new Customer();
            //model.Description = "Text Area Content";
            return View(customer);
        }

        // POST route for: /CustomerAccount/EditDetails
        // Save the updated data

        // POST route for: /CustomerAccount/EditDetails
        // Save the updated data
        [HttpPost]
        public ActionResult EditDetails(Customer cModel)
        {
            //cModel.Description = 
            var currentUser = (Customer)Session["currentUser"];
            //var cityId = Request.Form["citylist"];
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", cModel.CityId);                        
            cModel.LastUpdate = DateTime.Now;
            cModel.Email = currentUser.Email;
            cModel.Password = currentUser.Password;
            cModel.JoinedDate = currentUser.JoinedDate;

            //cModel.LastUpdate = DateTime.Now;
            //cModel.CityId = Convert.ToInt16(cityId);
            if (ModelState.IsValid)
            {
                db.Entry(cModel).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.Message = "Your details has been updated.";
            Session["currentUser"] = cModel;
            return View();
        }
        /*
        [HttpPost]
        public ActionResult EditDetails(Customer cModel)
        {
            //cModel.Description = 
            var currentUser = (Customer)Session["currentUser"];
            //var cityId = Request.Form["citylist"];
            
            ViewBag.Message = "Your details has been updated.";
            ViewBag.CityId = new SelectList(db.Cities, "CityId", "Name", cModel.CityId);
            cModel.LastUpdate = DateTime.Now;
            cModel.Email = currentUser.Email;
            cModel.Password = currentUser.Password;
            cModel.JoinedDate = currentUser.JoinedDate;
            //check whether the email is already exist or not
            //var customer = from p in db.Customers
            //               select p;
            //customer = customer.Where(s => s.Email.Equals(currentUser.Email));

            //cModel.LastUpdate = DateTime.Now;
            //cModel.CityId = Convert.ToInt16(cityId);
            if (ModelState.IsValid)
            {
                db.Entry(cModel).State = EntityState.Modified;
                db.SaveChanges();
            }
            
            Session["currentUser"] = cModel;
            return View();
        }
        */
        

        // GET route for: /CustomerAccount/Dashboard
        public ActionResult Dashboard()
        {
            //ViewData["viewCurrentUser"] = Session["currentUser"];
            return View();
        }

        // GET route for: /CustomerAccount/Logout
        public ActionResult Logout()
        {
            //ViewData["viewCurrentUser"] = Session["currentUser"];
            Session["currentUser"] = null;
            return View("Login");
        }

        public ActionResult Unsubscribe()
        {
            //ViewData["viewCurrentUser"] = Session["currentUser"];
            Customer current = (Customer)Session["currentUser"];
            Customer customer = db.Customers.Find(current.CustomerId);
            db.Customers.Remove(customer);
            db.SaveChanges();
            Session["currentUser"] = null;
            return View();
        }


        //method to populate city's dropdownbox
        public List<SelectListItem> getCities()
        {
            var cities = from p in db.Cities
                         select p;

PSP_EF/PSP_EF/Views/CustomerAccount/Create.cshtml
@model PSP_EF.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Customer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityId, "City")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityId", String.Empty)
            @Html.ValidationMessageFor(model => model.CityId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Suburb)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Suburb)
            @Html.ValidationMessageFor(model => model.Suburb)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOfBirth)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOfBirth)
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.JoinedDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.JoinedDate)
            @Html.ValidationMessageFor(model => model.JoinedDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastUpdate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastUpdate)
            @Html.ValidationMessageFor(model => model.LastUpdate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PSP_EF/PSP_EF/Views/CustomerAccount/Dashboard.cshtml
@using PSP_EF.Models
@model PSP_EF.Models.Customer

@{
    ViewBag.Title = "Dashboard";
    var cUser = (Customer)Session["currentUser"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style {
    <style type="text/css">
        .tab-pane .jumbotron
        {
            padding: 10px 10px 10px 10px;
            font-size: 15px;
        }
        .jumbotron .badge
        {
            margin-left: 1px;
            margin-right: 1px;
        }
        .jumbotron .btn
        {
            margin-left: 1px;
            margin-right: 1px;
        }
        .jumbotron img
        {
            max-width: 120px;
        }
    </style>
}

    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Personal Info</h3>
                </div>
                <div class="panel-body">
                    <div class="col-sm-4" style="padding-left:0px; padding-right:0px;">
                        <img src="../../Images/no_photo.jpg" class="img-thumbnail img-responsive"/>
                    </div>
                    <div class="col-sm-8">
                        <p style="margin-bottom:auto;">
                            <strong>Welcome back,</strong><br />
                            <a href="@Url.Action("EditDetails", "CustomerAccount")" data-toggle="tooltip" data-placement="auto" title="Click to Edit Details" id="userTooltip">@cUser.FirstName</a>
                        </p>
                        <p style="margin-bottom:auto;">Uid: @cUser.CustomerId</p>
                        <p style="margin-bottom:auto;">Lv. 5</p>
                        <div class="progress" data-toggle="tooltip" data-placement="auto" title="60%" id="levelTooltip" style="margin-bottom:auto;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <form role="form" action="#" method="post" style="text-align:center">
                        <div class="form-group">
                            <label for="actionType">What Do You Want to Post?</label>
                            <select class="form-control required" id="actionType" name="actionType">
                                <option selected="selected" value="1">Pet Adoption</option>
                                <option value="2">Pet Selling</option>
                                <option value="3">Pet Lost</option>
                                <option value="4">Pet Class</option>
                            </select>
                        </div>
                        <button type="button" class="btn btn-default btn-primary" style=" margin-left:auto; margin-right:auto;">Post Information</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-9">
            <ul class="nav nav-tabs" id="dashboardTab">
                <li><a href="#active" data-toggle="tab">Active&nbsp;<span class="badge pull-right">10</span></a></li>
                <li><a href="#hirer" data-toggle="tab">Hirer&nbsp;<span class="badge pull-right">2</span></a></li>
                <li><a href="#hiree" data-toggle="tab">Hiree&nbsp;<span class="badge pull-right">5</span></a></li>
                <li><a href="#rate" data-toggle="tab">Need Rating&nbsp;<span class="badge pull-right">3</span></a></li>
                <li><a href="#history" data-toggle="tab">History</a></li>
            </ul>
            <div class="tab-content" style="margin-top: 15px; margin-bottom: 15px;">
                <div class="tab-pane fade in active" id="active">
                    <div class="jumbotron container">
                        <div class="col-sm-3">
                            <img src="../../Images/no_photo.jpg" class="img-thumbnail img-responsive"/>
                        </div>
                        <div class="col-sm-9">
                            <h2>[Dummy] FireBird Sydney<span class="badge pull-right">Hiree</span><span class="badge pull-right">Pet Sitter</span></h2>
                            <p>[Dummy] Best pet sitters in Sydney! Incredible low price ...</p>
                            <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
                        </div>
                    </div>
                    <div class="jumbotron container">
                        <div class="col-sm-3">
                            <img src="../../Images/no_photo.jpg" class="img-thumbnail img-responsive"/>
                        </div>
                        <div class="col-sm-9">
                            <h2>[Dummy] Dog Talent<span class="badge pull-right">Hirer</span><span class="badge pull-right">Pet Class</span><span class="badge pull-right">Need Rating</span></h2>
                            <p>[Dummy] Teach your pet to stand ...</p>
                            <p><a class="btn btn-default" href="#">View details &raquo;</a><a class="btn btn-default" href="#">Rate &raquo;</a></p>
                        </div>
                    </div>
                    <div class="jumbotron container">
                        <div class="col-sm-3">
                            <img src="../../Images/no_photo.jpg" class="img-thumbnail img-responsive"/>
                        </div>
                        <div class="col-sm-9">
                            <h2>[Dummy] Fashion in Pet<span class="badge pull-right">Hirer</span><span class="badge pull-right">Pet Salon</span><span class="badge pull-right">Processing</span></h2>
                            <p>[Dummy] We make fashion in pets ...</p>
                            <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="hirer">
                    <p>Hirer</p>
                </div>
                <div class="tab-pane fade" id="hiree">
                    <p>Hiree</p>
                </div>
                <div class="tab-pane fade" id="rate">
                    <p>Need</p>
                </div>
                <div class="tab-pane fade" id="history">
                    <p>History</p>
                </div>
            </div>
        </div>
    </div>


@section scripts {
    <script>
        $(function () {
            $('#dashboardTab a:first').tab('show')
            $('#userTooltip').tooltip('hide')
            $('#levelTooltip').tooltip('hide')
        })
    </script>
}

PSP_EF/PSP_EF/Views/CustomerAccount/EditDetails.cshtml
@using PSP_EF.Models
@model PSP_EF.Models.Customer

@{
    ViewBag.Title = "Edit Details";
    var theCustomer = (Customer)Session["currentUser"];
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            text-align: left;
            font-size: large;
            padding: 6px 8px 6px 8px
        }
    </style>
}

@if (ViewBag.Message != null)
{
    <h6>@ViewBag.Message</h6>

    <h6>@Html.ActionLink("Go back to home page", "Dashboard", "CustomerAccount").</h6>
}
else
{
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h1 class="panel-title">Edit your profile</h1>
                    </div>
                    <div class="container" style="padding-top: 20px; padding-bottom: 20px;">
                        @if (@ViewBag.ErrorMessage != null)
                        {
                            <div class="alert alert-warning fade in">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                @ViewBag.ErrorMessage
                            </div>
                        }

                        <form role="form" class="col-lg-9 form-horizontal" action="@Url.Action("EditDetails", "CustomerAccount")" method="post", onsubmit="return validateEditForm()">
                            @Html.HiddenFor(model => model.CustomerId, new { @Value = theCustomer.CustomerId })
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.FirstName)" class="col-sm-4 control-label">First Name*</label>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control required", @placeholder = "Enter Your First Name", @Value = theCustomer.FirstName })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.LastName)" class="col-sm-4 control-label">Last Name*</label>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", @placeholder = "Enter Your Last Name", @Value = theCustomer.LastName  })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.DateOfBirth)" class="col-sm-4 control-label">Date of birth</label>
                                <div class="input-group date col-sm-8" id="DOBPicker" data-date-format="mm/dd/yyyy">
                                    @Html.TextBoxFor(model => model.DateOfBirth, new { @placeholder = "Select a Date", @Value = theCustomer.DateOfBirth, @class = "form-control", @readonly = true,  })
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="CityId" class="col-sm-4 control-label">City*</label>
                                <div class="col-sm-8">
                                    @Html.DropDownList("CityId", null, new { @class = "form-control required", @Value = theCustomer.CityId })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.Suburb)" class="col-sm-4 control-label">Suburb</label>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Suburb, new { @class = "form-control", @placeholder = "Enter Your Suburb", @Value = theCustomer.Suburb })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.Address)" class="col-sm-4 control-label">Address</label>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Enter Your Address", @Value = theCustomer.Address })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.Description)" class="col-sm-4 control-label">Description</label>
                                <div class="col-sm-8">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "Tell us about yourself", @Value = theCustomer.Description })
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="@Html.DisplayNameFor(model => model.Phone)" class="col-sm-4 control-label">Phone No</label>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Phone, new { @type = "tel", @class = "form-control", @placeholder = "Enter Your Phone Number", @Value = theCustomer.Phone })
                                </div>
                            </div>
                            <div class="col-sm-8 col-sm-offset-4">
                                <p>* indicates required fields</p>
                                <button type="submit" class="btn btn-default btn-primary">Save changes</button>
                                &nbsp;@Html.ActionLink("Cancel", "Dashboard", "CustomerAccount")
                            </div>
                        </form>
                        <div class="col-lg-3">
                            <h3>Avatar</h3>
                            <div class="form-group">
                                <p><img src="../../Images/no_photo.jpg" class="img-thumbnail img-responsive" max-height="80"/></p>
                                <input type="file" id="PetPicture">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts {
    <script type="text/javascript">
        $('#DOBPicker').datetimepicker({
            weekStart: 1,
            autoclose: 1,
            startView: 2,
            minView: 2,
            endDate: new Date(),
            forceParse: 1
        });
    </script>
}

PSP_EF/PSP_EF/Views/CustomerAccount/Login.cshtml
@model PSP_EF.Models.Customer

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}

@section style {
    <style type="text/css">
        body 
        {
            padding-top: 80px;
        }
        .btn-block
        {
            text-align: left;
            font-size: large;
            padding: 6px 8px 6px 8px
        }
    </style>
}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1 class="panel-title">Log in</h1>
                </div>
                <div class="container" style="padding-top: 20px; padding-bottom: 20px;">
                    @if (@ViewBag.Message != null)
                    {
                        <div class="alert alert-warning fade in">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            @ViewBag.Message
                        </div>
                    }

                    <form role="form" class="col-lg-8 form-horizontal" action="@Url.Action("Login", "CustomerAccount")" method="post">
                        @Html.ActionLink("Need an account? Sign up free!", "Register", "CustomerAccount")<br /><br />
                        <div class="form-group">
                            <label for="@Html.DisplayNameFor(model => model.Email)" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control required", @placeholder = "Enter Your Email" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="@Html.DisplayNameFor(model => model.Password)" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10">
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control required", @placeholder = "Enter Your Password" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-default btn-primary">Log in</button>
                        &nbsp;<a href="#">Forgot your password?</a>
                    </form>
                    <div class="col-lg-4">
                        <h3 style="margin-top:0px">Or Log in with</h3>
                        <button type="button" class="btn btn-default btn-block"><img src="http://janebutton.com/wp-content/uploads/2010/07/Facebook_icon.png" width="32" height="32"/>&nbsp;&nbsp;Facebook</button>
                        <button type="button" class="btn btn-default btn-block"><img src="http://janebutton.com/wp-content/uploads/2010/07/TwitterIcon.png" width="32" height="32"/>&nbsp;&nbsp;Twitter</button>
                        <button type="button" class="btn btn-default btn-block"><img src="http://janebutton.com/wp-content/uploads/2010/07/linkedin_icon.png" width="32" height="32"/>&nbsp;&nbsp;Linkedin</button>
                        <button type="button" class="btn btn-default btn-block"><img src="https://cdn1.iconfinder.com/data/icons/yooicons_set01_socialbookmarks/512/social_google_box_blue.png" width="32" height="32"/>&nbsp;&nbsp;Google</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PSP_EF/PSP_EF/Views/CustomerAccount/Unsubscribe.cshtml
@{
    ViewBag.Title = "Unsubscribe";
}

<h6>You have successfully unsubscribe from our system.</h6>

<h6>@Html.ActionLink("Go to main page", "Login", "CustomerAccount").</h6>